### ISSUE TITLE
[EPIC] Support for nacl, plan9, macos and Windows

### ISSUE THREAD

**Issue by SamuelMarks** [Fantom-foundation/go-lachesis#133]
AFAIK, this is what's required to have good support for the major Go-supported platforms:
- [x] Implement cross-platform Makefile replacement
Viable options: https://magefile.org, https://taskfile.org, https://rliebz.github.io/tusk, or even non Go ones like https://github.com/sagiegurari/cargo-make, https://github.com/casey/just
(also use this + Go code to replace Bash code with cross-platform code)
- [ ] Implement cross-platform [syslog](https://github.com/sirupsen/logrus/hooks/syslog) replacement
Viable options: `ReportEvent` on Windows; syslog on Linux (& [nacl](https://chromium.googlesource.com/native_client/nacl-glibc.git/+/master/misc/syslog.c)); [specialised syslog](https://github.com/brho/plan9/blob/f501206/sys/src/libc/9sys/syslog.c#L48) on plan9
- [ ] Implement script to traverse dependencies, extract build tags, map build tags to the file whence they're import (pun intended!), then produce a report of missing implementations per OS
- [ ] Provide example system init files (systemd [popular Linux init system], launchd [macOS], Windows Service, slew [plan9])
- [ ] Update goreleaser to produce packages for all the different OSs now supported
- [ ] CI/CD support
[Travis now supports Windows](https://blog.travis-ci.com/2018-10-11-windows-early-release), this needs to be implemented in our YAML.
AppVeyor needs to be implemented.
Options for plan9 need to be investigated.

**Comment by Maxime2** [comment]
gmake available on any platform, so it is a cross-platform tool.

PR #123 provides with custom hook for syslog (most unixes) and event log (windows) and stub for plan9 and nacl (pending implementation according system facilities).

**Comment by SamuelMarks** [comment]
I've built GNU Make on Windows in the past. It builds the `make.exe` without error.

However, even the most trivial `Makefile` failed to execute with it. If this has changed, can you compile GNU Make and see if you can compile anything, from Command Prompt, with it?

**Comment by SamuelMarks** [comment]
After some testing, involving the installation of precompiled versions of [`git`](https://git-scm.com), [`grep`](https://chocolatey.org/packages/grep), [`sed`](https://chocolatey.org/packages/sed), and [`make`](https://github.com/mbuilov/gnumake-windows) with the [official Go release](https://golang.org), was able to get `make vendor build` working without error in Command Prompt (`cmd.exe`).

Changing to the the build folder, and renaming `lachesis` to `lachesis.exe` and was able to confirm `lachesis version` worked as expected.

😮

Surprisingly to me—but not @Maxime2—there's no need to switch to another Makefile format!!!

**Comment by devintegral** [comment]
outdated
